dist: xenial
install: skip

script:
- uname -a
# - docker pull microsoft/azure-cli
# - docker pull mcr.microsoft.com/azure-cli
- docker run node ls
- docker run ubuntu ls
- docker run alpine ls
# - docker run robertdebock/debian ls
