dist: xenial
install: skip

script:
- uname -a
# - docker pull microsoft/azure-cli
# - docker pull mcr.microsoft.com/azure-cli
- cat /etc/docker/daemon.json
- docker pull travisci/ci-ubuntu-2004:packer-minimal-1605682785-1fb6ced8
- docker run node ls
- docker run ubuntu ls
- docker run alpine ls
# - docker run robertdebock/debian ls
